version: '3.3'

services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8080
    ports:
      - 8080:8080
    command: sh -c "python converter.py"
